name: "Pipeline"

on:
    push:
        branches:
            - "main"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: checkout repository
                uses: actions/checkout@v2

            -   name: Saludar
                run: |
                    echo "Me Llamaron!"